#!/bin/sh
#
# adjust

usage() {
    base="$(basename $0)"

    cat >&2 << EOF
Usage:
    $ $base up    | --up $(pfw)    : Move $JUMP pixels up.
    $ $base down  | --down $(pfw)  : Move $JUMP pixels down.
    $ $base left  | --left $(pfw)  : Move $JUMP pixels left.
    $ $base right | --right $(pfw) : Move $JUMP pixels right.
EOF

    test $# -eq 0 || exit $1
}

main() {
    . fwmrc
    wmenv

    widCheck "$2" && wid="$2" || usage 1

    # exit if wid is currently fullscreen
    grep -qrw "$wid" "$fsdir" 2> /dev/null && return 1

    case "$1" in
        up|--up)        wmv 0 -$JUMP $wid ;;
        down|--down)    wmv 0 +$JUMP $wid ;;
        left|--left)    wmv -$JUMP 0 $wid ;;
        right|--right)  wmv +$JUMP 0 $wid ;;
        -h|--help|help) usage 0           ;;
        *)              usage 1           ;;
    esac

    # move mouse to middle of window
    wmp -a $(($(wattr x $wid) + $(wattr w $wid) / 2)) \
           $(($(wattr y $wid) + $(wattr h $wid) / 2))
}

main "$@"
