#!/bin/sh
#
# autotile

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $base [tile method] [monitor]
EOF

    [ $# -eq 0 ] || exit "$1"
}

main() {
    . fwmrc
    wmgaps

    case "$1" in
        -g|--grid|grid)     METHOD="grid"   ;;
        -s|--split|split)   METHOD="split"  ;;
        -v|--vert|vert)     METHOD="vert"   ;;
        -l|--left|left)     METHOD="left"   ;;
        -r|--right|right)   METHOD="right"  ;;
        -b|--browse|browse) METHOD="browse" ;;
        -h|--help|help)     usage 0         ;;
        *)                  usage 1         ;;
    esac

    if mattr "$2"; then
        SCR="$2"
    else
        printf '%s\n\n' "$2 is not a connected screen."
        usage 1
    fi

    # init var
    nWindowsOld=0

    while :; do
        nWindows="$(listwindows "$SEC" | wc -l)"

        # compare number of current windows vs number of old windows
        if [ "$nWindows" -ne "$nWindowsOld" ]; then
            # exceptions to autotiling
            case "$(atomx WM_CLASS "$(lsw | tail -n 1)")" in
                python3|DiscordCanary) continue ;;
            esac

            # kill xmmv only when a window is dragged to the screen
            if [ "$nWindows" -gt "$nWindowsOld" ]; then
                pkill xmmv 2> /dev/null
            fi

            # autotile given monitor
            tile "$METHOD" "$SCR"

            # re-adjust counter
            nWindowsOld="$nWindows"
        fi

        sleep 0.10
    done
}

main "$@"
