#!/bin/sh
#
# closer

ARGS="$@"

usage() {
    cat >&2 << EOF
Usage: $(basename $0) [direction]
    -u | up:    Focus next window up.
    -l | left:  Focus next window left.
    -d | down:  Focus next window down.
    -r | right: Focus next window right.
    -h | help:  Show this help.
EOF

    test $# -eq 0 || exit $1
}

windowUp() {
    test "$PFW" = "0x00000001" && {
        mouseY="$(wmp -r | cut -d\  -f 2)"
        lsw | (xargs wattr yi; printf '%s\n' "$mouseY") | sort -nr | \
            sed -n "/$mouseY/{n;p}" | cut -d\  -f 2
    } || {
        lsw | xargs wattr yi | sort -nr | sed -n "/$PFW/{n;p}" | cut -d\  -f 2
    }
}

windowDown() {
    test "$PFW" = "0x00000001" && {
        mouseY="$(wmp -r | cut -d\  -f 2)"
        lsw | (xargs wattr yi; printf '%s\n' "$mouseY") | sort -n | \
            sed -n "/$mouseY/{n;p}" | cut -d\  -f 2
    } || {
        lsw | xargs wattr yi | sort -n | sed -n "/$PFW/{n;p}" | cut -d\  -f 2
    }
}

windowLeft() {
    test "$PFW" = "0x00000001" && {
        mouseX="$(wmp -r | cut -d\  -f 1)"
        lsw | (xargs wattr xi; printf '%s\n' "$mouseX") | sort -nr | \
            sed -n "/$mouseX/{n;p}" | cut -d\  -f 2
    } || {
        lsw | xargs wattr xi | sort -nr | sed -n "/$PFW/{n;p}" | cut -d\  -f 2
    }
}

windowRight() {
    test "$PFW" = "0x00000001" && {
        mouseX="$(wmp -r | cut -d\  -f 1)"
        lsw | (xargs wattr xi; printf '%s\n' "$mouseX") | sort -n | \
            sed -n "/$mouseX/{n;p}" | cut -d\  -f 2
    } || {
        lsw | xargs wattr xi | sort -n | sed -n "/$PFW/{n;p}" | cut -d\  -f 2
    }
}


main() {
    PFW="$(pfw 2> /dev/null || printf '%s\n' "0x00000001")"

    case "$1" in
        -u|--up|up)       focus --wid "$(windowUp)"    ;;
        -d|--down|down)   focus --wid "$(windowDown)"  ;;
        -l|--left|left)   focus --wid "$(windowLeft)"  ;;
        -r|--right|right) focus --wid "$(windowRight)" ;;
        -h|--help|help)   usage 0                      ;;
        *)                usage 1                      ;;
    esac
}

main $ARGS
