#!/bin/sh
# shellcheck disable=SC2015,SC2046
#
# cmdmenu

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $ $base
EOF

    test $# -eq 0 || exit "$1"
}

sel() {
    sleep 0.2
    wid="$(slw)"

    test "$wid" = "0x00000000" && exit 0

    case "$1" in
        delete) killw "$wid"                 ;;
        # resize) chwso -r "$wid"; xmrs "$wid" ;;
        # move)   chwso -r "$wid"; xmmv "$wid" ;;
        place)  chwso -r "$wid"; sh -c "wtp $(xrectsel '%x %y %w %h') $wid" ;;
    esac
}

new() {
    sleep 0.2

    fw=5
    fh=10
    ib=10
    ob=2

    xrectsel '%w %h %x %y' | {
            read -r w h x y
            w=$(( ( w - (ib + ob)*2 ) / fw ))
            h=$(( ( h - (ib + ob)*2 ) / fh ))
            exec urxvtc -g "${w}x${h}+${x}+${y}"
    }
}

open() {
    load "$(xsel -o)"
}

main() {
    . fwmrc
    wmenv
    wmgaps
    wmcolours

    case "$1" in
        -h|--help|help) usage 0 ;;
    esac

    # CWM-like right click
    X=$(($(wmp | cut -d\  -f 1) - $(mattr x "$PFM") - 10))
    Y=$(($(wmp | cut -d\  -f 2) - $(mattr y "$PFM") - 10))

    FONT=$(awk '/font/ {print $3}' < ~/.Xresources | cut -d',' -f 1)

    programs="new
move
place
resize
delete
open
shot
pfw"

    program=$(printf '%s\n' "$programs" | \
    dmenu -name "cmdmenu" -f -l 10 -fn "$FONT" -p " Do >" \
    -nf "#$ACTIVE" -sf "#$INACTIVE" -nb "#$INACTIVE" -sb "#$URGENT" -bc "#$ACTIVE" \
    -s "$(mattr d "$PFM")" -x $X -y $Y -w 100 -bw $BW)

    case "$program" in
        new)    new         ;;
        move)   sel move    ;;
        place)  sel place   ;;
        resize) sel resize  ;;
        delete) sel delete  ;;
        open)   open        ;;
        shot)   shot        ;;
        pfw)    shot "$PFW" ;;
    esac
}

main "$@"
