#!/bin/sh
#
# cmdmenu

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $ $base
EOF

    [ $# -eq 0 ] || exit "$1"
}

sel() {
    sleep 0.2
    wid="$(slw)"

    test "$wid" = "0x00000000" && exit 0

    case "$1" in
        shot)   shot "$wid"                  ;;
        delete) killw "$wid"                 ;;
        term)   killw -p "$wid"              ;;
        resize) chwso -r "$wid"; xmrs "$wid" ;;
        move)   chwso -r "$wid"; xmmv "$wid" ;;
        place)  chwso -r "$wid"; sh -c "wtp $(xrectsel '%x %y %w %h') $wid" ;;
    esac
}

new() {
    sleep 0.2

    fw=5
    fh=10
    ib=10
    ob=2

    xrectsel '%w %h %x %y' | {
            read -r w h x y
            w=$(( ( w - (ib + ob)*2 ) / fw ))
            h=$(( ( h - (ib + ob)*2 ) / fh ))
            exec urxvtc -g "${w}x${h}+${x}+${y}"
    }
}

open() {
    # use link handling program of your choosing
    load "$(xsel -o)"
}

menu() {
    # menu geometry
    X0="$(mattr x "$PFM")"
    Y0="$(mattr y "$PFM")"
    X=$(($(wmp | cut -d\  -f 1) - X0 - 20))
    Y=$(($(wmp | cut -d\  -f 2) - Y0 - 20))
}

main() {
    . fwmrc
    wmenv
    wmgaps
    wmenus
    dcolours

    PFM="$(pfm)"
    FONT=$(awk '/font/ {print $3}' < ~/.Xresources | cut -d',' -f 1)
    FH="15"
    W="100"
    PROMPT=" Do >"

    case "$1" in
        -h|--help|help) usage 0 ;;
        *)              menu    ;;
    esac

    L="$(printf '%s\n' "$processes" | wc -l)"

    process=$(printf '%s\n' "$processes" | \
dmenu -name "$(basename "$0")" -f -l "$L" -fn "$FONT" -p "$PROMPT" \
-nf "#$NF" -sf "#$SF" -nb "#$NB" -sb "#$SB" -bc "#$BC" \
-s "$(mattr d "$PFM")" -x $X -y $Y -w "$W" -h "$FH" -bw $BW)

    case "$process" in
        new)       new                ;;
        ssh)       sshmenu -m         ;;
        move)      sel move           ;;
        select)    wmenu -m           ;;
        resize)    sel resize         ;;
        delete)    sel delete         ;;
        terminate) sel term           ;;
        copy)      xsel -ob | xsel -i ;;
        open)      open               ;;
        shot)      shot               ;;
        pfw)       sel shot           ;;
        reset)     reboot             ;;
        off)       poweroff           ;;
    esac
}

main "$@"
