#!/bin/sh
#
# envreact

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $base

$autoreact must exist and be populated.
EOF

    [ $# -eq 0 ] || exit "$1"
}

react() {
    while read -r line; do
        prgs="${line#* }" cmd="${line%% *}" bin="${cmd%_*}" opt="${cmd#*_}"

        # test strings to see if program is running
        for prg in $prgs; do
            pgrep -f "$prg" > /dev/null && prg_alive=1
        done

        case "$prg_alive" in
            1)
                case "$opt" in
                    run) pgrep "$bin" > /dev/null || "$bin" & ;;
                    end) pkill "$bin" 2> /dev/null            ;;
                esac
                ;;
            *)
                case "$opt" in
                    end) pgrep "$bin" > /dev/null || "$bin" & ;;
                    run) pkill "$bin" 2> /dev/null            ;;
                esac
                ;;
        esac

        unset prg_alive
    done < "$autoreact"
}

main() {
    autoreact="$HOME/.autoreact"

    [ -f "$autoreact" ] || usage 1

    while :; do
        react
        sleep 1
    done
}

main "$@"
