#!/bin/sh
#
# ev

event() {
    wew | while IFS=: read ev wid; do
        case "$ev" in
            7)  wattr o "$wid" || focus -w "$wid" ;; # mouse enter
            16) wattr o "$wid" || open "$wid"     ;; # create window
            17)
                full -c "$wid"
                focus -w "$(lsw | tail -n 1)"
                ;; # destroy window
            18) ;; # unmap window
            19) ;; # map window
        esac
    done
}

event
