#!/bin/sh
#
# eventually

usage() {
    cat >&2 << EOF
Usage: $(basename $0) [-h|--help]
EOF

    test $# -eq 0 || exit $1
}

event() {
    wew | while IFS=: read ev wid; do
        case "$ev" in
            7)  wattr o "$wid" || focus -w "$wid" ;;
            16) wattr o "$wid" || open "$wid"     ;;
            17)
                full -c "$wid"

                wattr o "$wid" || { prev="$(lsw | tail -n 1)"
                    chwso -r "$prev"
                    chwb -s "$BW" -c "$ACTIVE" "$prev"
                    chwb -s "$BW" -c "$INACTIVE" "$wid"
                    wtf "$prev"
                }
                ;;
            18)
                ;;
        esac
    done
}

case "$1" in
    -h|--help|help)   usage 0 ;;
    *)                event   ;;
esac
