#!/bin/sh
# shellcheck disable=SC2015
#
# full

usage() {
    base="$(basename "$0")"

    cat >&2 << EOF
Usage:
    $ $base <wid> <screen>     : Toggle window fullscreen status.
    $ $base -c | --clean <wid> : Remove window from being fullscreen.
    $ $base -r | --reset       : Reset all fullscreen windows.
    $ $base -h | --help        : Show this help.
EOF

    test $# -eq 0 || exit "$1"
}

clean() {
    cleanWid=$1

    # search all files for matching wid
    grep -qrw "$cleanWid" "$fsdir" && {
        screenIdFile=$(grep -rH "$cleanWid" "$fsdir" | cut -d: -f 1)

        test ! -z "$cleanWid" && {
            chwb -s "$BW" -c "$ACTIVE" "$wid"
            sh -c "wtp $(grep -w "$wid" "$screenIdFile")"
        }

        rm "$screenIdFile"
    }

    exit 0
}

reset() {
    rm "$fsdir"/* 2> /dev/null
    exit 0
}

main() {
    . fwmrc
    wmenv
    wmcolours

    case "$1" in
        -h|--help|help)   usage 0    ;;
        -r|--reset|reset) reset      ;;
        -c|--clean|clean) clean "$2" ;;
        *)
            case $# in
                0)
                    widCheck "$PFW" && wid="$PFW" || usage 1
                    SCR="$(mattr i "$PFW")"
                    ;;
                1)
                    widCheck "$1" && wid="$1" || usage 1
                    SCR="$(pfm)"
                    ;;
                2)
                    widCheck "$1" && wid="$1" || usage 1
                    mattr "$2" && SCR="$2" || {
                        printf '%s\n' "$2 is not a connected screen."
                        exit 1
                    }
                    ;;
            esac
            ;;
    esac

    # clean wid if already focused
    grep -qrw "$wid" "$fsdir" && {
        clean "$wid"
        return
    }

    # focus fullwid if it exists
    test -e "$fsdir/$SCR" && {
        focus wid "$(cut -d\  -f 5 "$fsdir/$SCR")"
        return
    }

    # save window info to disk
    wattr xywhi "$wid" > "$fsdir/$SCR"

    # perform fullscreen operations
    chwb -s 0 "$wid"
    chwso -r "$wid"
    sh -c "wtp $(mattr xywh "$SCR") $wid"
}

main "$@"
