#!/bin/sh
#
# fwmrc

# check there is a display running
test -z "$DISPLAY" && return 1

# check if arg 1 is an integer
intCheck() {
    test $1 -ne 0 2> /dev/null
    test $? -ne 2 || return 1
}

widCheck() {
    case "$1" in
        0x*) wattr "$1" ;;
        *)   return 1   ;;
    esac
}

name() {
    test $# -eq 0 && return 1
    for wid in $@; do
        lsw -a | grep -q "$wid" && {
            xprop -id "$wid" WM_CLASS | cut -d\" -f 2
            unset -v wid
        } || {
            printf '%s\n' "Please enter a valid window id." >&2
            unset -v wid
            return 1
        }
    done
}

class() {
    test $# -eq 0 && return 1
    for wid in $@; do
        lsw -a | grep -q "$wid" && {
            xprop -id "$wid" WM_CLASS | cut -d\" -f 4
            unset -v wid
        } || {
            printf '%s\n' "Please enter a valid window id." >&2
            unset -v wid
            return 1
        }
    done
}

process() {
    test $# -eq 0 && return 1
    for wid in $@; do
        lsw -a | grep -q "$wid" && {
            xprop -id "$wid" _NET_WM_PID | cut -d\  -f 3
            unset -v wid
        } || {
            printf '%s\n' "Please enter a valid window id." >&2
            unset -v wid
            return 1
        }
    done
}

# list windows on currently focused wid screen
listcurrent() {
    PFW="$(pfw 2> /dev/null || printf '%s\n' "0x00000001")"
    SCR="$(mattr i $PFW)"
    mattr si $(lsw) | grep "$SCR" | cut -d\  -f 1
}

wmenv() {
    fwmdir=${fwmdir:-/tmp/fwm}

    fsdir=${fsdir:-$fwmdir/fs}
    test ! -d "$fsdir" && mkdir -p "$fsdir"

    PFW="$(pfw 2> /dev/null || printf '%s\n' "0x00000001")"
    BW="$(grep "borderwidth" $HOME/.cwmrc | cut -d\  -f 2)"
}

wmgaps() {
    PRI="$(lsm -p)"
    TGAP="$(grep "gap" $HOME/.cwmrc | cut -d\  -f 2)"
    BGAP="$(grep "gap" $HOME/.cwmrc | cut -d\  -f 3)"
    LGAP="$(grep "gap" $HOME/.cwmrc | cut -d\  -f 4)"
    RGAP="$(grep "gap" $HOME/.cwmrc | cut -d\  -f 5)"
}

wmcolours() {
    BACK="$(grep "color menufg" $HOME/.cwmrc | cut -d\" -f 2 | sed 's/#//')"
    ACTIVE="$(grep "color activeborder" $HOME/.cwmrc | cut -d\" -f 2 | sed 's/#//')"
    URGENT="$(grep "color urgencyborder" $HOME/.cwmrc | cut -d\" -f 2 | sed 's/#//')"
    INACTIVE="$(grep "color inactiveborder" $HOME/.cwmrc | cut -d\" -f 2 | sed 's/#//')"
}
