#!/bin/sh
# shellcheck disable=SC2015
#
# fwmrc

# check there is a display running
test -z "$DISPLAY" && return 1

# check if arg 1 is an integer
intCheck() {
    test "$1" -ne 0 2> /dev/null
    test "$?" -ne 2 || return 1
}

widCheck() {
    case "$1" in
        0x*) wattr "$1" ;;
        *)   return 1   ;;
    esac
}

# list windows on focused screen or given screen
listwindows() {
    mattr "$1"

    case "$?" in
        0)
            SCR="$1"
            ;;
        *)
            PFW="$(pfw 2> /dev/null || printf '%s\n' "0x00000000")"
            SCR="$(mattr i "$PFW")"
            ;;
    esac

    mattr si $(lsw) | grep "$SCR" | cut -d\  -f 1
}

wmenv() {
    fwmdir=${fwmdir:-/tmp/fwm}

    fsdir=${fsdir:-$fwmdir/fs}
    test ! -d "$fsdir" && mkdir -p "$fsdir"
    tiledir=${movedir:-$fwmdir/tile}
    test ! -d "$tiledir" && mkdir -p "$tiledir"
    movedir=${movedir:-$fwmdir/move}
    test ! -d "$movedir" && mkdir -p "$movedir"
    groupdir=${groupdir:-$fwmdir/group}
    test ! -d "$groupdir" && mkdir -p "$groupdir"

    PFW="$(pfw 2> /dev/null || printf '%s\n' "0x00000000")"
    export PFW BW=1 JUMP=20
}

wmgaps() {
    PRI="$(lsm -p)"
    PFM="$(pfm)"
    export PRI PFM
    export TGAP=10 BGAP=40 LGAP=10 RGAP=20 IGAP=20
}

wmcolours() {
    export ACTIVE="EFEFEF" URGENT="B23450" INACTIVE="101010"
}

wmgroup() {
    export activegrp="$groupdir/active"
    export inactivegrp="$groupdir/inactive"
}
