#!/bin/sh
#
# programs

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $ $base -m | menu   : Show as a window.
    $ $base -c | center : Show as a window centered above focused window.
    $ $base -h | help   : Show this help.
EOF

    test $# -eq 0 || exit "$1"
}

width() {
    ps=$(txtw -f "$FONT" "$PROMPT")
    char="$(printf '%s\n' "$programs" | wc -L)"
    W=$(echo "($ps + $char * 4.9 + 8) / 1" | bc)
}

menu() {
    # menu geometry
    X0="$(mattr x "$PFM")"
    Y0="$(mattr y "$PFM")"
    X=$(($(wmp | cut -d\  -f 1) - X0 - 25))
    Y=$(($(wmp | cut -d\  -f 2) - Y0 - 25))
}

center() {
    width
    H=$((nPrograms * FH))

    # finding x y cords for centering
    if [ "$PFW" = "0x00000000" ]; then
        X=$(($(mattr w "$PFM")/2 - W/2 - 10))
        Y=$(($(mattr h "$PFM")/2 - H/2 - 10))
    else
        X0="$(mattr x "$PFM")"
        Y0="$(mattr y "$PFM")"
        X=$(($(wattr x "$PFW") + $(wattr w "$PFW")/2 - W/2 - X0))
        Y=$(($(wattr y "$PFW") + $(wattr h "$PFW")/2 - H/2 - Y0))

        # move mouse to middle of window
        wmp -a $(($(wattr x "$PFW") + $(wattr w "$PFW") / 2)) \
               $(($(wattr y "$PFW") + $(wattr h "$PFW") / 2))
    fi
}

main() {
    . fwmrc
    wmenv
    wmgaps
    wmenus
    dcolours

    PFM="$(pfm)"
    FONT=$(awk '/font/ {print $3}' < ~/.Xresources | cut -d',' -f 1)
    FH="15"
    W="150"
    PROMPT=" Load >"

    nPrograms="$(printf '%s\n' "$programs" | wc -l)"
    test "$nPrograms" -eq 0 && exit 1

    case "$1" in
        -m|menu)        menu    ;;
        -c|center)      center  ;;
        -h|--help|help) usage 0 ;;
        *)              usage 1 ;;
    esac

    printf '%s\n' "$programs" | \
dmenu -name "$(basename "$0") " -f -l "$nPrograms" -fn "$FONT" -p "$PROMPT" \
-nf "#$NF" -sf "#$SF" -nb "#$NB" -sb "#$SB" -bc "#$BC" \
-s "$(mattr d "$PFM")" -x $X -y $Y -w "$W" -h "$FH" -bw $BW | /bin/sh &
}

main "$@"
