#!/bin/sh
# shellcheck disable=SC2015,SC2046
#
# programs

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $ $base
EOF

    test $# -eq 0 || exit "$1"
}

main() {
    . fwmrc
    wmenv
    wmgaps
    wmenus
    wmcolours

    case "$1" in
        -h|--help|help) usage 0 ;;
    esac

    FONT=$(awk '/font/ {print $3}' < ~/.Xresources | cut -d',' -f 1)

    # menu geometry fit to display
    SCR="$(pfm)"
    X0="$(mattr x "$SCR")"
    Y0="$(mattr y "$SCR")"
    X=$(($(wmp | cut -d\  -f 1) - X0))
    Y=$(($(wmp | cut -d\  -f 2) - Y0))

    W="150"
    FH="15"
    L="$(printf '%s\n' "$programs" | wc -l)"
    H="$((FH * (L + 1)))"

    test "$X" -lt "$LGAP" && X="$LGAP"
    test "$Y" -lt "$TGAP" && Y="$TGAP"

    Xboundary="$(($(mattr w "$SCR") - W - RGAP))"
    test "$X" -gt "$Xboundary" && X=$Xboundary

    Yboundary="$(($(mattr h "$SCR") - H - BGAP))"
    test "$Y" -gt "$Yboundary" && Y=$Yboundary

    wmp -a "$((X + X0 + 15))" "$((Y + Y0 + 20))"

    printf '%s\n' "$programs" | \
dmenu -name "cmdmenu" -f -l "$L" -fn "$FONT" -p " To >" \
-nf "#$ACTIVE" -sf "#$INACTIVE" -nb "#$INACTIVE" -sb "#$URGENT" -bc "#$ACTIVE" \
-s "$(mattr d "$(pfm)")" -x $X -y $Y -w "$W" -h "$FH" -bw $BW | /bin/sh &
}

main "$@"
