#!/bin/sh
#
# open

. fwmrc

wattr "$1" && wid="$1" || exit 1

case "$(name $wid)" in
    "")                      exit 1 ;;
    "WM_CLASS")              exit 1 ;;
    "WM_CLASS:  not found.") exit 1 ;;
esac

case "$(class $wid)" in
    URxvt)
        case "$(wname $wid)" in
            [mosh]*)
                # group add 0 $wid
                ;;
            *)
                # group add 1 $wid
                ;;
        esac
        ;;
    Firefox)
        # group add 2 $wid
        ;;
    mpv)
        move -m $wid
        # group add 3 $wid
        ;;
    discord)
        ;;
    TelegramDesktop)
        ;;
    Blender)
        ;;
    obs)
        ;;
    Lutris)
        # group add 5 $wid
        ;;
    Steam)
        # group add 5 $wid
        ;;
    steam_app_439370)
        ;;
esac
