#!/bin/sh
#
# open

ARGS="$@"

main() {
    . fwmrc
    wmgaps
    wmcolours

    wid="$1"
    case "$(name "$wid")" in
        "qutebrowser")
            group add 2 "$wid"
            ;;
        "gl")
            group add 3 "$wid"
            chwso -r "$wid"
            chwb -s "$BW" -c "$ACTIVE" "$wid"
            chwb -s "$BW" -c "$INACTIVE" "$PFW"
            wtf "$wid"
            exit 0
            ;;
        "discord")
            group add 4 "$wid"
            exit
            ;;
        # games
        "doomx64vk.exe"|"midair-win64-test.exe")
            group add 5 "$wid"
            ;;
    esac

    W=$(wattr w $wid 2> /dev/null)
    H=$(wattr h $wid 2> /dev/null)
    test -z $W && continue
    test -z $H && continue

    X=$(($(wmp | cut -d\  -f 1) - $W / 2))
    Y=$(($(wmp | cut -d\  -f 2) - $H / 2))

    wtp $X $Y $W $H $wid

    focus -w "$wid"
}

main $ARGS
