#!/bin/sh
#
# pmenu

usage() {
    base=$(basename $0)

    cat >&2 << EOF
Usage:
    $base
EOF

    test $# -eq 0 || exit $1
}

main() {
    . fwmrc
    wmgaps
    wmcolours

    # CWM-like right click
    X=$(($(wmp | cut -d\  -f 1) - $(mattr x $PRI) - 10))
    Y=$(($(wmp | cut -d\  -f 2) - $(mattr y $PRI) - 10))

    FONT=$(awk '/font/ {print $3}' < ~/.Xresources | cut -d',' -f 1)

    programs="urxvt
steam
discord
qutebrowser
pizero
obs"

    program=$(printf '%s\n' "$programs" | \
    dmenu -name "pmenu" -f -l 10 -s 0 -fn "$FONT" -p "Run >" \
    -nf "#$ACTIVE" -sf "#$URGENT" -nb "#$INACTIVE" -sb "#$INACTIVE" -bc "#$ACTIVE" \
    -x $X -y $Y -w 120 -bw $BW)

    case "$program" in
        urxvt)  urxvtc ;;
        pizero) urxvtc -e sh -c "mosh $program" ;;
        *)      $program ;;
    esac | ${SHELL:-"/bin/sh"} & > /dev/null 2>&1
}

main "$@"
