#!/bin/sh
# shellcheck disable=SC2015,SC2046
#
# sshmenu

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $ $base
EOF

    test $# -eq 0 || exit "$1"
}

width() {
    ps=$(txtw -f "$FONT" "$PROMPT")
    char="$(printf '%s\n' "$hosts" | wc -L)"
    W=$(echo "($ps + $char * 4.9 + 8) / 1" | bc)
}

menu() {
    # menu geometry
    X0="$(mattr x "$PFM")"
    Y0="$(mattr y "$PFM")"
    X=$(($(wmp | cut -d\  -f 1) - X0 - 25))
    Y=$(($(wmp | cut -d\  -f 2) - Y0 - 25))
}

center() {
    width
    H=$((nHosts * FH))

    # finding x y cords for centering
    if [ "$PFW" = "0x00000000" ]; then
        X=$(($(mattr w "$PFM")/2 - W/2 - 10))
        Y=$(($(mattr h "$PFM")/2 - H/2 - 10))
    else
        X0="$(mattr x "$PFM")"
        Y0="$(mattr y "$PFM")"
        X=$(($(wattr x "$PFW") + $(wattr w "$PFW")/2 - W/2 - 10 - X0))
        Y=$(($(wattr y "$PFW") + $(wattr h "$PFW")/2 - H/2 - 10 - Y0))

        # move mouse to middle of window
        wmp -a $(($(wattr x "$PFW") + $(wattr w "$PFW") / 2)) \
               $(($(wattr y "$PFW") + $(wattr h "$PFW") / 2))
    fi
}

main() {
    . fwmrc
    wmenv
    wmgaps
    dcolours

    PFM="$(pfm)"
    FONT=$(awk '/font/ {print $3}' < ~/.Xresources | cut -d',' -f 1)
    FH=15
    W="150"
    PROMPT=" Mosh >"

    hosts="$(grep -w "host" ~/.ssh/config | cut -d\  -f 2)"
    nHosts=$(printf '%s\n' "$hosts" | grep -cv "$PFW")
    test "$nHosts" -eq 0 && exit 1

    case "$1" in
        -m|menu)        menu    ;;
        -c|center)      center  ;;
        -h|--help|help) usage 0 ;;
    esac

    host=$(printf '%s\n' "$hosts" | \
dmenu -name "$(basename "$0")" -f -l "$nHosts" -fn "$FONT" -p "$PROMPT" \
-nf "#$NF" -sf "#$SF" -nb "#$NB" -sb "#$SB" -bc "#$BC" \
-s "$(mattr d "$PFM")" -x $X -y $Y -w "$W" -h "$FH" -bw $BW)

    test -n "$host" && urxvtc -g 85x22 -e sh -c "mosh $host || ssh $host"
}

main "$@"
