#!/bin/sh
#
# tile
usage() {
    base=$(basename $0)

    cat >&2 << EOF
Usage:
    $ $base <wid> <screen>
    $ $base [-c|--clean] <wid>
    $ $base [-r|--reset]
    $ $base [-h|--help]
EOF

    test $# -eq 0 || exit $1
}
