#!/bin/sh
#
# watcher

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $base
EOF

    [ $# -eq 0 ] || exit "$1"
}

main() {
    autogroup="$HOME/.autogroup"

    wew | while read -r ev wid; do
        case "$ev" in
            CREATE)
                wattr o "$wid" || {
                    NAME="$(atomx WM_NAME "$wid")"
                    CLASS="$(atomx WM_CLASS "$wid")"

                    case "$CLASS" in
                        qutebrowser)
                            [ "$(wattr xywh "$wid")" = "50 50 800 600" ] && {
                                move center "$wid" "$(lsm -p)"
                            }
                            ;;
                        obs)              ;;
                        discord|Steam)    ;;
                        midair*)
                            move full "$wid"
                            ;;
                        kdenlive)
                            move center "$wid"
                            ;;
                    esac

                    # autogroups
                    while read -r line; do
                        group="$(printf '%s\n' "$line" | cut -d\  -f 1)"
                        class="$(printf '%s\n' "$line" | cut -d\  -f 2)"

                        [ "$class" = "$CLASS" ] && {
                            case "$CLASS" in
                                obs)
                                    case "$NAME" in
                                        OBS*)    ;;
                                        *) break ;;
                                    esac
                                    ;;
                                Steam) break ;;
                            esac

                            group -a "$group" "$wid"
                            break
                        }
                    done < "$autogroup"
                }
                ;;
        esac
    done
}

main "$@"
