#!/bin/sh
#
# watcher

usage() {
    base=$(basename "$0")

    cat >&2 << EOF
Usage:
    $base
EOF

    [ $# -eq 0 ] || exit "$1"
}

main() {
    . fwmrc
    wmenv
    wmgaps

    wew | while read -r ev wid; do
        case "$ev" in
            CREATE)
                NAME="$(atomx WM_NAME "$wid")"
                CLASS="$(atomx WM_CLASS "$wid")"

                wattr o "$wid" && {
                    case "$CLASS" in
                        lemonbar)
                            chwso -l "$wid"
                            ;;
                    esac
                } || {
                    case "$CLASS" in
                        qutebrowser)
                            [ "$(wattr xywh "$wid")" = "50 50 800 600" ] && {
                                wrs 200 200 "$wid"
                                move center "$wid" "$(lsm -p)"
                            }
                            ;;
                        obs)           continue ;;
                        discord|Steam) continue ;;
                        ?idair*)
                            move full "$wid" "$(lsm -p)"
                            ;;
                        python3|DiscordCanary)
                            move center "$wid"
                            ;;
                        gl)
                            sleep 0.2
                            ;;
                        *)
                            wmv -a $(wmp) "$wid"
                            ;;
                    esac

                    # autogroups
                    [ -f "$autogroup" ] && {
                        while read -r line; do
                            group="$(printf '%s\n' "$line" | cut -d\  -f 1)"
                            class="$(printf '%s\n' "$line" | cut -d\  -f 2)"

                            [ "$class" = "$CLASS" ] && {
                                group -a "$group" "$wid"
                                break
                            }
                        done < "$autogroup"
                    }

                    chwso -r "$wid"
                    wtf "$wid"
                }
                ;;
            DESTROY)
                # focus window underneath pointer if window is deleted
                under > /dev/null && focus -w $(under)
                ;;

            ENTER)
                # only provide sloppy focus when cwm is not running
                pgrep cwm > /dev/null 2>&1 || {
                    wattr o "$wid" || focus -w "$wid" nojump
                }
                ;;
        esac
    done
}

autogroup="$HOME/.autogroup"

main "$@"
