#!/bin/sh
# shellcheck disable=SC2015
#
# wid

usage() {
    cat >&2 << EOF
Usage: $(basename "$0") "search string"
EOF

    test $# -eq 0 || exit "$1"
}

showAll() {
    for wid in $($LSWCMD); do
        printf '%s\n' "$wid $(atomx WM_NAME "$wid")"
        printf '%s\n' "$wid $(atomx WM_CLASS "$wid")"
    done
}

main() {
    test $# -eq 0 && usage 1

    . fwmrc

    case "$1" in
        -h|--help|help)
            usage 0
            ;;
        -a|all)
            LSWCMD="lsw -a"
            shift
            ;;
        -u|hid)
            LSWCMD="lsw -u"
            shift
            ;;
        *)
            LSWCMD="lsw"
            ;;
    esac

    showAll | grep -i "$@" | cut -d\  -f 1 | sort | uniq | sed 1d
}

main "$@"
