#!/bin/sh
# shellcheck disable=SC2015
#
# wid

usage() {
    cat >&2 << EOF
Usage: $(basename "$0") "search string"
EOF

    test $# -eq 0 || exit "$1"
}

findName() {
    for wid in $(lsw); do
        printf '%s\n' "$wid $(atomx "$wid" WM_NAME)"
    done
}

findClass() {
    for wid in $(lsw); do
        printf '%s\n' "$wid $(atomx "$wid" WM_CLASS)"
    done
}


showAll() {
    findName
    findClass
}

main() {
    test $# -eq 0 && usage 1

    case "$1" in
        -h|--help|help) usage 0 ;;
    esac

    . fwmrc

    showAll | grep -i "$@" | cut -d\  -f 1 | sort | uniq
}

main "$@"
