#!/bin/sh
#
# wid

usage() {
    cat >&2 << EOF
Usage: $(basename "$0") "search string"
EOF

    [ $# -eq 0 ] || exit "$1"
}

showAll() {
    for wid in $($LSWCMD); do
        printf '%s\n' "$wid $(atomx WM_NAME "$wid")"
        printf '%s\n' "$wid $(atomx WM_CLASS "$wid")"
    done
}

main() {
    [ $# -eq 0 ] && usage 1

    . fwmrc

    case "$1" in
        -h|--help|help)
            usage 0
            ;;
        -a|all)
            LSWCMD="lsw -a"
            shift
            ;;
        -o|ovr)
            LSWCMD="lsw -o"
            shift
            ;;
        -u|hid)
            LSWCMD="lsw -u"
            shift
            ;;
        *)
            LSWCMD="lsw"
            ;;
    esac

    showAll | grep -Fi "$@" | grep -v "wid" | cut -d\  -f 1 | sort | uniq
}

main "$@"
