#!/bin/sh
#
# wmenu

. fwmrc
wmcolours

FONT=$(awk '/lemon/ {print $3}' < ~/.Xresources |  head -n 1 | cut -d',' -f 1)
LINES=$(lsw | wc -l)

for wid in $(lsw); do
    printf '%s\n' "$wid $(class $wid) | $(wname $wid)"
done | \
dmenu -name "wmenu" -f -b -l $LINES -s 0 -i -fn $FONT -p "Window:" \
-nf "#$ACTIVE" -sf "#$URGENT" -nb "#$BACK" -sb "#$BACK" | \
cut -d\  -f 1 | focus
