#!/bin/sh
#
# wmenu

usage() {
    base=$(basename $0)

    cat >&2 << EOF
Usage:
    $base -b | bar  <-a|-u> : Show as a bar.
    $base -m | menu <-a|-u> : Show as a floating window.
    $base -h | help         : Show this help.
EOF

    test $# -eq 0 || exit $1
}

menu() {
    # CWM-like right click
    X=$(($(wmp | cut -d\  -f 1) - $(mattr x $PRI) - 10))
    Y=$(($(wmp | cut -d\  -f 2) - $(mattr y $PRI) - 10))

    output="$(for window in $($LSWCMD); do
               printf '%s\n' "$window $(class $window) | $(wname $window)"
           done)"

   char="$(printf '%s\n' "$output" | wc -L)"
   W=$(echo "$char * 6.9" | bc)

   wid="$(printf '%s\n' "$output" | sort -k 2 | \
          dmenu -name "wmenu" -f -l $nWindows -s 0 -i -fn $FONT -p "Window >" \
          -nf "#$ACTIVE" -sf "#$URGENT" -nb "#$INACTIVE" -sb "#$INACTIVE" -bc "#$ACTIVE" \
          -x $X -y $Y -w $W -bw $BW | cut -d\  -f 1)"
}

bar() {
    wid="$(for window in $($LSWCMD); do
               printf '%s\n' "$window $(class $window) | $(wname $window)"
           done | sort -k 2 | \
           dmenu -name "wmenu" -f -l $nWindows -b -x -2 -y 2 -s 0 -i -fn $FONT -p "Window >" \
           -nf "#$ACTIVE" -sf "#$URGENT" -nb "#$INACTIVE" -sb "#$INACTIVE" -bc "#$ACTIVE" \
           -bw 1 | cut -d\  -f 1)"
}

main() {
    . fwmrc
    wmenv
    wmgaps
    wmcolours

    FONT=$(awk '/font/ {print $3}' < ~/.Xresources | cut -d',' -f 1)

    case "$2" in
        -a|all) LSWCMD="lsw -a" ;;
        -u|hid) LSWCMD="lsw -u" ;;
        *)      LSWCMD="lsw"    ;;
    esac

    nWindows=$($LSWCMD | wc -l)
    test $nWindows -eq 0 && exit 1

    case "$1" in
        -b|bar)  bar     ;;
        -m|menu) menu    ;;
        -h|help) usage 0 ;;
        *)       usage 1 ;;
    esac

    focus -w "$wid"
}

main "$@"
